# Default schema for Fidgit
---

# Define all constant values here. For colours, use [R, G, B] or [R, G, B, A].
# Reference constants with ?constant_name
:constants:
  # General constants (strings and numbers).
  :scroll_bar_thickness: 12

  # Gosu::Color constants
  :none: [0, 0, 0, 0]

  :black: [0, 0, 0]
  :white: [255, 255, 255]

  :very_dark_gray: [50, 50, 50]
  :dark_gray: [100, 100, 100]
  :gray: [150, 150, 150]
  :light_gray: [200, 200, 200]

  :red: [255, 0, 0]
  :green: [0, 0, 255]
  :blue: [0, 0, 255]

  :dark_red: [100, 0, 0]
  :dark_green: [0, 100, 0]
  :dark_blue: [0, 0, 100]

# Default element attributes.
:elements:
  :Button: # < Label
    :background_color: ?dark_gray
    :border_color: ?light_gray
    :border_thickness: 2
    :shortcut_color: ?red
    :padding_top: 2
    :padding_right: 4
    :padding_bottom: 2
    :padding_left: 4

    :disabled:
      :background_color: ?very_dark_gray
      :border_color: ?gray

    :hover:
      :background_color: ?gray

  :ColorPicker:
    :indicator_height: 30

  :ColorWell: # < RadioButton
    :height: 32
    :outline_color: ?gray
    :width: 32

    :checked:
      :border_color: ?very_dark_gray

  :ComboBox: # < Button
    :background_color: ?dark_gray
    :border_color: ?white

  :Composite: # < Container
    :padding_top: 0
    :padding_right: 0
    :padding_bottom: 0
    :padding_left: 0

  :Container: # < Element
    {}

  :Element:
    :align_h: :left
    :align_v: :top
    :background_color: ?none
    :background_image: nil
    :border_color: ?none
    :border_thickness: 0
    :color: ?white
    :font_height: 30
    :font_name: :default
    :padding_top: 2
    :padding_right: 4
    :padding_bottom: 2
    :padding_left: 4


  :FileBrowser: # < Composite
    :pattern: "*.*"
    :show_extension: true

  :Grid: # < Packer
    :cell_background_color: ?none
    :cell_border_color: ?none
    :cell_border_thickness: 0

  :Group: # < Packer
    :padding_top: 0
    :padding_right: 0
    :padding_bottom: 0
    :padding_left: 0

  :Horizontal: # < Grid
    {}

  :HorizontalScrollBar: # < ScrollBar
    :height: ?scroll_bar_thickness

  :ImageFrame: # <Element
    :padding_top: 0
    :padding_right: 0
    :padding_bottom: 0
    :padding_left: 0

  :Label: # < Element
    :justify: :left
    :icon_position: :left

    :disabled:
      :color: ?gray

  :List:
    :background_color: ?light_gray
    :border_color: ?white

  :List::Item:
    :border_thickness: 0

  :MainPacker: # < Packer
    :border_thickness: 0
    :padding_top: 0
    :padding_right: 0
    :padding_bottom: 0
    :padding_left: 0
    :spacing_h: 0
    :spacing_v: 0

  :MenuPane:
    :background_color: ?very_dark_gray

  :MenuPane::Item: # < Button
    :border_color: ?none
    :border_thickness: 0

  :MenuPane::Separator: # < Label
     :line_height: 2
     :background_color: ?black

  :Packer: # < Container
    :spacing_h: 4
    :spacing_v: 4

  :RadioButton: # < Button
    :checked:
      :border_color: ?blue

  :ScrollArea: # < Composite
    {}

  :ScrollBar: # < Composite
    :background_color: ?none
    :border_color: ?none
    :handle_color: ?dark_red
    :rail_color: ?very_dark_gray
    :rail_width: ?scroll_bar_thickness

  :ScrollWindow: # < Composite
    :scroll_bar_thickness: ?scroll_bar_thickness
    :border_color: ?light_gray
    :border_thickness: 1

  :Slider: # < Element
    :background_color: ?none
    :border_color: ?dark_gray
    :groove_color: ?light_gray
    :handle_color: ?dark_green

  :Slider::Handle: # < Element
    :background_color: ?dark_blue

  :TextArea: # < Composite
    :background_color: ?very_dark_gray
    :border_color: ?light_gray
    :caret_color: ?red
    :caret_period: 500 # In milliseconds
    :line_spacing: 0
    :selection_color: ?dark_gray

    :focused:
      :border_color: ?green

  :TextLine: # < Element
    :justify: :left
    :padding_top: 0
    :padding_right: 0
    :padding_bottom: 0
    :padding_left: 0

  :ToggleButton: # < Button
    :toggled:
      :border_color: ?red

  :ToolTip: # < Label
    :background_color: ?very_dark_gray
    :font_height: 20
    :border_color: ?white
    :padding_top: 2
    :padding_right: 4
    :padding_bottom: 2
    :padding_left: 4

  :Vertical: # < Grid
    {}

  :VerticalScrollBar: # < ScrollBar
    :width: ?scroll_bar_thickness
